name: driveapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.10
  firebase_app_check: ^0.3.0
  google_sign_in: ^6.1.5

  # Media & Files
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.10.0
  path_provider: ^2.1.1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1

  # QR & Scanner
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

  # UI & Navigation
  go_router: ^14.0.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # Auth & Security
  local_auth: ^2.3.0
  local_auth_android: ^1.0.45
  permission_handler: ^11.3.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  uuid: ^4.3.3
  logger: ^2.0.2

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

# ðŸ”¹ APP ICON CONFIG (TOP LEVEL)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
